### ISSUE TITLE
How best to connect posts of two different CPTs?

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#12]
We need to map people to projects, and projects to people. Ideally, this will be a relationship that would go both ways—so you could add a person to a project from the edit person page, and you could also add a project to a person from the edit project page.

That said, I think it we can only do a one-way relationship, it would make more sense to assign a person to a project, especially since we'll already be doing some of that in terms of assigning ourselves, the referrer, etc. 

What's the best way to accomplish this?

**Comment by sarahmonster** [comment]
Note that we already have a sort of rudimentary link right now, in that there's a custom meta box for "influencers". For now, we could manually enter the person's ID, but that's terrible for at least sixteen different reasons. 

Quick thought on how best to approach this:

It may be sensible to enter *all* people as "people" CPTs—including ourselves. That way, we can associate any number of people with a project. Since each person has a type, we'll be able to tell contextually if that person is an influencer, a striker, a consultant, etc.

THEN, instead of having custom meta fields for strikers and influencers attached to the project, we just have a repeatable field (similar to [what I mentioned for timezones](https://github.com/a8cteam51/strikebase/pull/19#issuecomment-254475502)) for "people" attached to the project. (For easyness, maybe leave "referrer" as its own field.)

Two options here: drop-down (http://fieldmanager.org/docs/fields/select/) or autocomplete (http://fieldmanager.org/docs/fields/autocomplete/) but I think the latter would be far more elegant without requiring more work. We can run a custom query to get all the people and store their names and IDs in an array to provide the datasource for the autocomplete, which will be way more user-friendly in the long run than a drop-down.

In terms of how to best save the data, I'm not sure what's most sensible here—I am assuming a string of IDs (which we'd then have to build a function to parse out on the front-end) stored as a single text field, but I'm not quite sure.

If it helps here, I can prototype what I think would be sensible from a UI perspective.

**Comment by sarahmonster** [comment]
http://fieldmanager.org/docs/misc/storing-data-unserialized/

**Comment by danielwrobert** [comment]
As mentioned in Slack, we should be able to use a datasource in a select field and query by post type. The only thing I recall running into an issue was with the repeatable fields. Fieldmanager was a bit finicky there. But we wouldn't need a repeatable field there would we? Just using a select to choose a project or person should suffice, it seems.

**Comment by sarahmonster** [comment]
Solved via #26.
