### ISSUE TITLE
Custom post type setup

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#2]
We'll need at least two CPTs: people and projects. We'll also need organisations—but this may make most sense as a custom taxonomy.

**People**
- name
- type (influencer/contractor)
- organisation(s) [connected to org taxonomy]
- projects(s) [connected to project CPT]
- notes

- WordPress.com username
- email(s)
- phone
- location/address(?)
- timezone
- Twitter, Facebook, Instagram(?)

- date last contacted (for now, this should be an input, but in the future we may be able to pull from Zendesk automatically)

**Projects**
- title
- status (on hold/in progress/launched/cold/dropped)
- genre
- host
- type (consultant, custom design & development, development only, strikestart, etc)

- strikers [connected to WordPress.com username, maybe ability to designate individual role within the project; ie lead, design, project management, development, client contact, etc]
- influencers [connected to people CPT]
- organisation [connected to org taxonomy]
- referrer [connected to WordPress.com username]

- notes

- staging site
- production site
- Github repo

- date received
- date started
- estimated launch date
- actual launch date
- date of last contact (as above, should come from ZD eventually but for v1 makes sense as an input)

**Comment by sarahmonster** [comment]
Looking at the list above, we've got a few more things that probably make most sense as custom taxonomies:

- person type (influencer/contractor)
- project status (on hold/in progress/launched/cold/dropped)
- project genre
- project host
- project type (consultant, custom design & development, development only, strikestart, etc)

in addition to organisations!

**Comment by sarahmonster** [comment]
Something I've been trying to track with incoming strikes is "influential-ness", which is tricky to measure. However, we can get a few numbers, notably:

- Alexa rank (global/America, although global feels like the best indicator)
- number of monthly US visitors (via Quantcast)
- # of Twitter followers

These would be great to see at-a-glance, since it would allow us to easily get a sense of the "influentialness" or importance of a project (although there are obviously other components that would affect this). Are there any other numbers we should be taking into account here?

**Comment by michiecat** [comment]
I don't think we need location/address for the person CPT since it doesn't affect our work on a regular basis. The most relevant location info for us would be timezone. 

For the "People" CPT...what are your thoughts on simplifying it a bit and treating "Organizations" as a type of "Person"? For example, the CPT could be:

"Client"
- type: influencer / contractor / individual / organization
- other meta stays the same.

I'm seeing the benefits of entering each person separately though, but just wonder if it would end up being too tedious to enter information for clients in an organization with whom we interact with once or twice.

**Comment by michiecat** [comment]
Here are proposals for the types of inputs for each of these meta items: 

**People**
- name  _(Text Input (the "Title")_
- type (influencer/contractor) _taxonomy_
- organisation(s) [connected to org taxonomy] _taxonomy_
- projects(s) [connected to project CPT] _taxonomy_
- notes _textarea_

- WordPress.com username _text input_
- email(s) _textarea (for multiple emails)_
- phone _text input_
- location/address(?) _propose removing_
- timezone _text input so we can be specific_
- Twitter, Facebook, Instagram(?) _i suggest combining these into single "Social Media Accounts" textarea for simplicty's sake, so we can enter all of their relevant accounts_

- date last contacted (for now, this should be an input, but in the future we may be able to pull from Zendesk automatically) _agreed with input_

**Projects**
- title _Main Title Field_
- status (on hold/in progress/launched/cold/dropped) _taxonomy_
- genre _taxonomy_
- host _taxonomy_
- type (consultant, custom design & development, development only, strikestart, etc) _taxonomy_

- strikers [connected to WordPress.com username, maybe ability to designate individual role within the project; ie lead, design, project management, development, client contact, etc] _For simplicty in v1 -- a textarea where we can manually list strikers and their roles_
- influencers [connected to people CPT]  _so this would pull in associated people?_
- organisation [connected to org taxonomy] _taxonomy_
- referrer [connected to WordPress.com username] _could we keep this simple by manually entering this into a text input_

- notes _textarea_

- staging site _text input_
- production site _text input_
- Github repo _text input_

- date received _text input_
- date started _text input_
- estimated launch date _text input_
- actual launch date _text input_
- date of last contact (as above, should come from ZD eventually but for v1 makes sense as an input) _text input_

**Comment by sarahmonster** [comment]
This list looks really good to me! If we're agreed on them—and they can always be changed later, as we decide what does and doesn't work—we can start setting up the CPTs, taxonomies, and metadata boxes now. 

What's the most straightforward way of doing this these days? I always just use a generator, but there may be a more efficient way...
