### ISSUE TITLE
Use a drop-down input for timezone

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#21]
Timezone should be a drop-down, to ensure normalisation across all entries and so we can deal with data programmatically should we need to. 

Easily done with field manager:
http://fieldmanager.org/docs/fields/select/

We'd just need to decide how to populate that timezone data—generating a list directly from PHP's available timezones might be the most sensible option.

**Comment by michiecat** [comment]
>generating a list directly from PHP's available timezones might be the most sensible option

+1! That way we don't need to define our own.
