### ISSUE TITLE
Better entry of social media accounts

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#22]
Entering social media accounts in a free-form textarea feels laborious, and it's unclear how it's done—do we separate them by newline, or by comma? Do we type in the whole address, including a URL?

I think a more elegant solution here would be a repeatable input field. This would consist of a drop-down to select the network (Twitter, Pinterest, Facebook, etc) plus an input box for the username. 

At first, there would only be a single input field showing, but there'd be a + button to add another. (This button could display contextually, once there'd already been one added, perhaps?)

Clicking the "add another" button would bring up a second instance of the repeatable input field, with its own drop-down and input box. 

I'm not sure how difficult this will be to implement, but we'll need to consider how to store this sort of data (serialised array?) and that will impact how we enter the data now, so I think it's worth investigating sooner rather than later, if for no reason other than to sort out an approach. (See #12 for a similar issue in terms of multiple entries for one input.)

**Comment by sarahmonster** [comment]
I just ran across this, which indicates it's very likely possible: http://fieldmanager.org/docs/misc/storing-data-unserialized/

**Comment by sarahmonster** [comment]
I think using repeatable fields here (much like we've done for project to people connections) could be super useful, but I suspect that will only allow us to use single fields. Ideally I think it would be good if the data entry looked something like this:

![social-media-entry](https://cloud.githubusercontent.com/assets/376315/19838866/cc19c9fe-9ecf-11e6-9ea5-d34012c01147.gif)

So there'd be a drop-down to select the network, and then an input box where you'd enter the username. Ideally our front-end stuff would be smart enough to figure out if you'd used a @ or a full URL and strip out any extra bits, so the output would be consistent even if data entry weren't. 

Thoughts? @michiecat since you'll be doing a lot of data entry it'll be helpful to get your input here.

**Comment by michiecat** [comment]
Your screenshot above looks really useful and helpful and it's a big plus one from me. However if I read correctly, we'd need custom functionality to link a dropdown box to the input box?  

I also wouldn't mind plain input boxes for each network. What benefits do repeatable fields offer that just using plain input boxes would (besides saving space?) I'm open to repeatable fields, I'm just curious if they add more work than is necessary for v1.

Also since we're the only ones entering data, I think it's OK to put instructions above the fields (such as not including "@") for v1. Making the front end output checking could be a nice enhancement for v2.

**Comment by michiecat** [comment]
Also I was thinking -- a non-repeatable field list of inputs would be faster since I wouldn't have to click a drop-down to choose a network. I could just click inside a box and fill it in.

**Comment by sarahmonster** [comment]
> I also wouldn't mind plain, non-repeatable input boxes for each network. What benefits do repeatable fields offer that just using plain input boxes would (besides saving space?) I'm open to repeatable fields, I'm just curious if it adds more work than is necessary for v1.

I can definitely set this up for now. When we originally discussed setting up CPTs in #2, you mentioned that you'd prefer a textarea to a series of input boxes, but I think that might be more awkward, which is why I filed the issue. 

For reference, right now entering social media stuff looks something like this:

<img width="494" alt="screenshot 2016-10-31 11 05 50" src="https://cloud.githubusercontent.com/assets/376315/19852266/437a7bd0-9f5a-11e6-893c-10c6e54907db.png">

I can definitely work on a PR that would add major social media accounts as inputs instead, and then we can fine-tune as required for a v2.

**Comment by michiecat** [comment]
Ah yes, I did suggest a text area at first, but I see how that's not efficient. I agree with simple inputs for v1 and if it doesn't work for us, we can take a different approach if needed in v2.

**Comment by sarahmonster** [comment]
Okay, so I can do a PR to split these into individual networks. Here's what I'd suggest we start with:

- Twitter
- Facebook
- Youtube
- Instagram

The most relevant social media accounts are those where you have followers (and a follower count) or where you post stuff (like "WordPress is the best/worst!") so something like Pinterest, while popular, is a bit less relevant here. Other networks we should include?

**Comment by michiecat** [comment]
I think starting with those four makes the most sense for the reasons you gave.
