### ISSUE TITLE
Set up private internal site for app

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#3]
This should require a proxy to access, and should be running the theme we'll start building here momentarily! Beyond that I shouldn't think we'd need anything specific.

**Comment by danielwrobert** [comment]
I've set the site up. I don't believe we necessarily need a proxy. Flagging it and setting it to private should be sufficient enough, based on what I've found. If we find we need a proxy requirement, we can add this later but I don't think that'll be needed.
