### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#33]
This is a bit indulgent, but it would be nice to put together a simple little graphic element, if for no reason other than so I can set up the Slack->Github integration with a better icon than a camping emoji.

A custom favicon will actually help us with the usability side of things in the long term, since it helps us find tabs in our tab-soup. (I assume everyone else also suffers from Endless Tab Syndrome.)

So: thoughts? Ideas? So far I have "something vaguely military-ish in feeling" and "maybe a tent?" but that's pretty vague and I'd love to hear your ideas!

**Comment by michiecat** [comment]
I like the tent icon in Slack, actually. Something along those lines would be cute. My initial thought was something database related, but the tent/camping idea is more fun. Other words for visuals:

- command center
- control pad
- campfire
- campground
- military base
- headquarters
- military insignia or badge
- dock or port (as in for ships)
- central system
- database
- filing system
- folders
- library
- card file

**Comment by michiecat** [comment]
In keeping with our alien/space theme:

- star base (like a command center for a star system)
- futuristic starship database
- a scientific-themed database 
- museum-themed (each item in strikebase is like a museum specimen)

**Comment by sarahmonster** [comment]
❤️ these ideas! Once we have v1 nailed down I'm putting this at the top of my list.

**Comment by sarahmonster** [comment]
Some initial logo ideas! Pretty rough right now (and we'll add colour) but should be enough to get a consensus on direction...

![strikebase-logo-mock-a](https://cloud.githubusercontent.com/assets/376315/20280619/20346400-aaa5-11e6-828f-6ada6c936610.png)
![strikebase-logo-mock-b](https://cloud.githubusercontent.com/assets/376315/20280621/20372ba4-aaa5-11e6-9f3d-48215c549865.png)
![strikebase-logo-mock-c](https://cloud.githubusercontent.com/assets/376315/20280620/2035888a-aaa5-11e6-9a15-63cc45846678.png)

**Comment by michiecat** [comment]
They're all great, but the flag just speaks to me. There's a rhythm and flow with that one that I find appealing. Maybe due to the way the text is positioned under the flag. That's my vote.

**Comment by danielwrobert** [comment]
I really do like all three of these. I would cut the first one, however, because it feels more like camping to me. Even though I really like it. The last two are a bit more applicable, in my opinion. I really love the flag but I also like the more compact feel of the flight pin (if that makes any sense - I am trying to think of a better way to explain that).

Additionally, I believe the text should be StrikeBase with the capital B, from what I recall discussing.

**Comment by sarahmonster** [comment]
Sounds like the flag is a winner—I'll fine-tune a bit and work on a colour scheme/style guide next.

I'd like to propose we nix the camel-casing—it's a bit dated at this point and it interrupts the flow of the word in an awkward way. It's also grammatically irresponsible, and we don't need it in order to understand how to pronounce/understand the portmanteau.

WordPress itself may use this convention because it was trendy at the time it came out, but a lot of other a8c properties don't (Simplenote, Jetpack, Polldaddy, Longreads, Cloudup).

Related reading:
https://pando.com/2013/01/03/was-2012-the-year-camelcase-died/
http://www.nytimes.com/2009/11/29/magazine/29FOB-onlanguage-t.html?_r=0

**Comment by sarahmonster** [comment]
I coloured the flag logo & started working with it a while ago, but its shape made for pretty awkward awkwardness:

<img width="502" alt="screenshot 2017-03-27 20 46 10" src="https://cloud.githubusercontent.com/assets/376315/24374939/856ddfee-132e-11e7-9952-54770ae0d62e.png">


so I played around with the shapes, to see if I could make it a bit more pliable:
<img width="735" alt="screenshot 2017-03-27 20 41 04" src="https://cloud.githubusercontent.com/assets/376315/24374700/c081251a-132d-11e7-984f-e5acd6802317.png">

...and ended up not liking any of them very much. Instead, I opted for a simpler version in the header, with the full version (sans text) as a background element in #102:

![strikebase-header](https://cloud.githubusercontent.com/assets/376315/24375060/e6580c9e-132e-11e7-8a48-88b774e71fc1.gif)

Happy to take feedback here—I think I've been staring at it far too long.
