### ISSUE TITLE
Design component: filters

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#48]
Related to #41, we should also allow for filtering of people and projects on the primary listing/archive pages, via either a drop-down select or a series of buttons, depending.

Here's what I think would make sense to filter for:

PEOPLE:
- [ ] type of person (by default perhaps only influencers would show up?)

PROJECTS:
- [ ] status
- [ ] genre
- [ ] host (MAYBE)
- [ ] type of project

Anything else that would be helpful to filter by?

See also #40, which I started a PR to solve but may be better handled by direct filtering on the page itself. 

We'll need this designed (@sarahsemark) and then built out as a React component (@danielwrobert).

**Comment by michiecat** [comment]
>by default perhaps only influencers would show up?
+1, this would be a useful default for us. 

I suggest status ("active") as the default filter for projects. What say ye?

**Comment by sarahmonster** [comment]
This is roughly how I envision this working, except with proper CSS animations:

![filter](https://cloud.githubusercontent.com/assets/376315/22653286/d80e2ef4-ec80-11e6-8ff2-6d36a45dc75f.gif)

More examples of the pattern here: http://ui-patterns.com/patterns/TableFilter

**Comment by michiecat** [comment]
Overall I like the functionality and it felt right to me when I stepped through the prototype. Questions:

1. Are there intentions to allow multiple filters? The "Clear all filters" link suggests that. 
2. Should we show which filters are active, outside of the dropdown box? Many of the examples in the link you shared (http://ui-patterns.com/patterns/TableFilter) show the active filter(s) up front.

**Comment by michiecat** [comment]
And for projects, I would say yes for filtering by host. I can see a use-case where we'd want to pull out all sites hosted by Fancy Scalable Platform, for example, if they want to find all the high-impact projects that they host in order to write marketing material on it.

**Comment by sarahmonster** [comment]
> Are there intentions to allow multiple filters? The "Clear all filters" link suggests that.

I'm thinking it would make sense to allow multiple filters: once you click on an item in the list it shows only records corresponding to that filter, but then you could add additional filters as well. (So you could show all people classed as contractors and strikers at once, for instance.)

In the case of projects, we actually have multiple filter drop-downs, so you'd be able to filter in all kinds of different combinations.

> Should we show which filters are active, outside of the dropdown box? Many of the examples in the link you shared (http://ui-patterns.com/patterns/TableFilter) show the active filter(s) up front.

I thought about this for a while beforehand, because it does offer some increased usability at the expense of a more cluttered interface, especially where we have multiple filtration options. Hovering over or clicking on the filter drop-down will allow users to see the currently active filters, as well as remove and add filters, but that's obviously less visible than having everything visible by default.

In the interests of simplicity, I'd prefer to omit it for the time being. If we determine it's something that we need or that's missing in terms of a UX experience, it shouldn't be too hard to implement.

**Comment by michiecat** [comment]
>In the interests of simplicity, I'd prefer to omit it for the time being. If we determine it's something that we need or that's missing in terms of a UX experience, it shouldn't be too hard to implement.
Sounds good to me!
