### ISSUE TITLE
Functionality plan-o-rama!

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#5]
Let's talk about functionality! What do we need for a v1 minimum-viable-product, and what's going to be a nice add-on? 

For v1, let's focus on the bare-minimum functionality we absolutely require in order to get away from spreadsheets _now_.

If we can hash out a broad map of these pages/functionalities, we can break each stage up into individual issues and discuss the tasks in more detail as we work on them.

Initial thoughts:

v1
- CPTs and custom taxonomies set up as per #2 
- ability to enter data in some way (can be via wp-admin for now)
- ability to look at all data from the frontend and not burst into tears
- "person" page
- "project" page
- listings page for both "people" and "projects"

v2 to ∞
- intelligent/robust searching (#55)
- inline editing of data from frontend ❤️ (#32)
- integration with Github API (open issues feed, dashboard numbers, high-priority issues, etc) (#70)
- all dashboard functionality (see #1 for wireframe) #35, #36, #38 
- Zendesk API integration (show recent tickets in people/project view, show on dashboard, etc) (#71)
- automated "date of last contact" (#71)
- dashboard alerts for check-ins based on date of last contact (#35)
- Twitter API functionality (at-a-glance view of influencer tweets and/or potential lead-sourcing; may be just as easily done via existing social media tools) (#72)
- notifications (I don't know if we'd need these really)
- statistics (issues closed, tickets dealt with, sites launched this year/quarter, average site launch time, etc etc etc) (#38)

**Comment by sarahmonster** [comment]
Something I've been trying to track with incoming strikes is "influential-ness", which is tricky to measure. However, we can get a few numbers, notably:

- Alexa rank (global/America, although global feels like the best indicator)
- number of monthly US visitors (via Quantcast)
- # of Twitter followers

These would be great to see at-a-glance, since it would allow us to easily get a sense of the "influentialness" or importance of a project (although there are obviously other components that would affect this). Are there any other numbers we should be taking into account here?

**Comment by michiecat** [comment]
> ability to enter data in some way (can be via wp-admin for now)

+1 to WP Admin and/or Calypso to start with. Keeping it as simple as possible for v1.

> "person" page

Some of our "people" are individuals, such as Mish. Others are an organization, like F|S. For simplicity's sake, I propose treating organizations as people. So F|S would be entered as a "Person". We could perhaps create a tag-like taxonomy to indicate if a person is an "individual" or "organization". We might even want to rename the "Person" CPT to "Influencer" or "Client".

**Comment by sarahmonster** [comment]
I wonder about that from a data perspective—I think people and organisations have different properties, and we may end up running into some oddness if we make them the same kind of data.

If we treat one organisation as a single "person" entity, how would we track email addresses/phone numbers, as well as the names of the individual people who may contact us representing that organisation?

I figured that we'd have an entry for each individual person, and then attach them to an organisation if there is one—but that the organisation would really be supplementary information.

My wireframe-thought for what a "person" page would look like:

![img_0589](https://cloud.githubusercontent.com/assets/376315/18998822/3b3c3002-8732-11e6-95ba-70a428531a37.jpg)

**Comment by michiecat** [comment]
> If we treat one organisation as a single "person" entity, how would we track email addresses/phone numbers, as well as the names of the individual people who may contact us representing that organisation?

All valid points! Your wireframe looks well thought out to me. My main concern was wanting to avoid having dozens of entries for people with whom we communicate with only once or twice. Perhaps we can handle that by only entering someone into the site if they communicate with us a certain number of times.

**Comment by sarahmonster** [comment]
That's a good point. Ideally if we have robust, intelligent searching (or automated integration with Zendesk contacts!), this wouldn't be too much of an issue, either from a data entry perspective or from a "finding what you need" perspective. 🙏

**Comment by sarahmonster** [comment]
Closing since all of the functionality discussed has been broken down into individual tickets (all referenced above.)
