### ISSUE TITLE
How many projects/people do we show to a page?

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#50]
We should probably show a larger number than the default, since these are pretty short lists. How do we handle pagination—should these pages infinite scroll (this might be awkward) or should be just show a certain number (maybe 50 or 100) to a page and then paginate?

**Comment by michiecat** [comment]
+1 for pagination in the v2 state. If we feel like we want IS we can add it in a later iteration. 

50 sounds like a good number to test the waters with.
