### ISSUE TITLE
Display people's faces

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#51]
There are two ways of going about this: we could try to pull data from WordPress.com (since we'll have their usernames; not sure how this would work or if the information is exposed via our API) or we can just use the email address to grab their gravatar, which definitely seems like the most straightforward approach and probably makes the most sense here unless we need to pull additional WordPress.com data.

https://en.gravatar.com/site/implement/images/

**Comment by michiecat** [comment]
My vote is for gravatars. Keepin it simple with a system that already works.
