### ISSUE TITLE
IS on People archive is broken

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/strikebase#56]
When clicking on the "Older People" link at the bottom of the people archive, IS tries to load the older folks (hahaha) but doesn't return anything. IS should work on `is_archive()` but since this is a custom template, we might need to add some conditionals to make sure it's working properly.

**Comment by sarahmonster** [comment]
Worth noting we're leaning toward nixing IS entirely (see #50) so it'd probably make more sense to just remove it & paginate here instead.
