### ISSUE TITLE
Add theme to production site

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#6]
We'll need to commit this theme to SVN and activate it on the production site—I can put together an initial zip file if needed. Generally I skip the following files:

- assets/stylesheets
- .gitignore
- package.json
- gulpfile.js

We can do most of the development on Github, but push to SVN every now and again as required. This will also allow us to test things on a shared server while we're working on them.

**Comment by michiecat** [comment]
I'll take care of the initial commit this week! I can generate a ZIP file that omits the development files/folders.

**Comment by michiecat** [comment]
Theme committed, closing this issue.
