### ISSUE TITLE
Set up custom metaboxes for projects CPT

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#7]
Adding these is always a little bit hairy, so I'm not sure precisely the best way of going about it. I always just [write out all the code manually](https://github.com/sarahmonster/wanderlist/blob/master/includes/admin/wanderlist-admin.php), but that may not be the most straightforward approach. 

"People" box:
- [ ] strikers (connected to WordPress.com username, text input)
- [ ] influencers custom field (connected to people CPT)
- [ ] referrer (same as "strikers" above, text input for now)

"Links" box (all text inputs):
- [ ] staging site
- [ ] production site
- [ ] Github repo

"Dates" box (all date-pickers):
- [ ] date received
- [ ] date started
- [ ] estimated launch date
- [ ] actual launch date
- [ ] date of last contact

**Comment by danielwrobert** [comment]
Manually would be one option. Another method I've used on a couple of our projects has been the FieldManager plugin. It's used on VIP so we're good to use it. It's still a very code-heavy config but it offers a good amount of options/features. I'd be glad to help set that up, if you'd like!

**Comment by sarahmonster** [comment]
That sounds like a great plan! If the config is in the code that'll be ideal, since it means we won't have to replicate the settings a bunch of times on all our local environments *and* on the production site. 👍 

(Assigning this one to you!)

**Comment by sarahmonster** [comment]
Closed via #f645b62.
