### ISSUE TITLE
Design an initial iconset

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#74]
This list is subject to change as prototypes develop:

Primary navigation:
- [ ] dashboard
- [ ] people
- [ ] projects
- [ ] organisations

Filter functionality (#48):
- [x] close
- [x] caret/arrow
- [ ] selected item

Client check-ins:
- [x] late check-in
- [x] upcoming check-in

People types:
- [ ] influencer/beneficiary
- [ ] striker
- [ ] automattician (?)
- [ ] contractor

Project statuses:
- [ ] active
- [ ] launched
- [ ] complete

Actions (v3):
- [x] edit
- [x] add
- [ ] delete

**Comment by sarahmonster** [comment]
Additional icons for projects (see #79)

Host:
- [ ] Pressable
- [ ] VIP
- [ ] .com
- [ ] VIP Go
- [ ] other .org

Genre:
We have a *lot* of these and they're likely going to be in flux—perhaps just start with broader or focus categories?
- [ ] music
- [ ] entertainment
- [ ] non-profit
- [ ] causes
- [ ] small business
- [ ] restaurants
Where there's already rather a lot of categories here, I could see filtering (#48) being pretty unwieldy as well. It may make sense to make genre hierarchical (#93) and only show an icon for the top-level category.

Type:
Again, we may want to refine/consider this list as data is available, since some of these categories may merge into one another a bit.
- [ ] consulting
- [ ] design
- [ ] development
- [ ] maintenance
- [ ] migration
- [ ] redesign
- [ ] refresh
- [ ] theme-review
- [ ] tune-up

**Comment by michiecat** [comment]
Yeahhh...those lists are rather long and I see your point about them getting unwieldy as we go along. Hierarchical genres sounds like a good approach for now (as I commented on the related issue). 

I can see "tune-up" falling under "consulting", so we could merge those two at least, perhaps under "consulting"? That's probably worth a separate discussion though.

**Comment by sarahmonster** [comment]
Created a p2 post to discuss this in more detail—I'll refine the required icon list once we've discussed our taxonomies in more detail internally.
