### ISSUE TITLE
Populate with initial content

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/strikebase#9]
When CPTs/Taxonomies are ready, we can start gathering and entering the initial content into the site. I'll start by filling in the active projects and organizations. We can use this thread to track the process and note anything that needs to be addressed.

**Comment by sarahmonster** [comment]
Note that if we already have some of this data in spreadsheets 😭 we can potentially look into using a CSV-to-WordPress plugin (https://wordpress.org/plugins/wp-ultimate-csv-importer/ or similar) to import the data automatically, and assign it to a given CPT. 

Because our production site is on WordPress.com, we'd need to do this on a local staging site in order to install the plugin, but once that's done it would be an easy export/import operation.

**Comment by michiecat** [comment]
The only concern I have is that it would involve creating new (or massaging existing) spreadsheets to follow the data structure in the CPT. But it would save time entering the data in the CPT. I'm opening to seeing how it works locally, and take it from there. Also, since some of the CPTs will be linked (People and Projects), we may need to go back through the data after the import to assign those if those connections can't be created automatically during import.

**Comment by sarahmonster** [comment]
Most of the CSV-to-WordPress plugins allow you to basically map your columns to specific fields in the WordPress data structure, so you shouldn't have to work on the spreadsheets themselves much or change the column names. That said, I'm not certain how consistent our existing data is, which may make it less worth the hassle.

Invariably there will be some unavoidable manual data-entry, but if we already have some good data, this may be a way to speed things up a smidge. If you don't have a local dev environment set up already, I can try testing this on my local machine to see how much data I'm able to extract, and then I can share an export file.

**Comment by michiecat** [comment]
After thinking about it I'm fine with entering it manually to start with. There's not a TON of data to enter (for example in the case of projects there are only 51 total in the spreadsheet) and I think it can be done in 3 or 4 sprints.

**Comment by michiecat** [comment]
Update: all of our active clients, organizations, strikers, and contractors have been entered. I haven't included cold projects in this round.

Currently working on entering projects:

- [ ] Launched projects (in-progress)
- [ ] Active projects
- [ ] Upcoming projects

**Comment by michiecat** [comment]
Will do a huge push on Feb 18-21 to get the remaining data entered. ;-) Marking it here so you can all hold me accountable.

**Comment by michiecat** [comment]
Added 11 new projects and 2 new people this weekend. Adding projects is a bit time-consuming due to the need to look up all of the dates and relevant links. My new plan is to add at least 5 projects a day, every day. That's 35 projects a week. At that rate, everything will be entered before March 31st.

**Comment by michiecat** [comment]
Closing this because the content entry is now complete! We just need to decide how to handle suggested strikes (they're listed in an issue in our team GH repo for now) but that can be a separate discussion.
