### ISSUE TITLE
Project genre should be hierarchical

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikebase#93]
We currently have only 15 genres in our available dataset, but this is with lots of projects still missing. I suspect it would help a great deal to make genres hierarchical, so we'd better be able to sort them. We'll want to chat (probably internally) about how we actually go about organising that data as well, but making it hierarchical would definitely making filtering (#48) a great deal easier as well. 

Any objections?

**Comment by michiecat** [comment]
No objections on my end to making genres hierarchical, especially if it'll make filtering easier.
